name: Cargo Build & Test & check toolchain

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ matrix.toolchain }}
      - name: Install Clippy for the toolchain
        run: rustup component add clippy --toolchain ${{ matrix.toolchain }}
      - name: Install fmt for the toolchain
        run: rustup component add rustfmt --toolchain ${{ matrix.toolchain }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt --all --check --verbose
      - run: cargo audit

      - name: Checkout
        uses: actions/checkout@v2
      - name: Install other dependencies
        run: sudo apt-get install moreutils dos2unix
      - name: Check encoding
        run: isutf8 **/*
      - name: Check line endings
        run: bash .github/workflows/scripts/check_line_endings.sh
      - name: Check TODOs
        run: bash .github/workflows/scripts/check_todos.sh
      - name: Check Unwraps
        run: bash .github/workflows/scripts/check_unwrap.sh